trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: 'Deploy Apache HTTP Server'
  jobs:
  - job: CopyRepo
    displayName: 'Copy HTML from Repo on to Azure VM'
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'Azure VM EnergyWise'
        sourceFolder: '$(Build.SourcesDirectory)/'
        contents: '**'
        targetFolder: '/var/www/html/'
        readyTimeout: '20000'